[build]
  # Disattivo completamente qualsiasi processo di build
  # e pubblico direttamente l'HTML statico
  base = "."
  publish = "."
  command = "echo 'Skipping build phase'"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 