[build]
  # Disattiva completamente il processo di build
  command = "cp -r apps/website/public/* ."
  publish = "."

# Redirezione fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
