[build]
  base = "."
  command = "pnpm install --no-frozen-lockfile && cd apps/website && NEXT_TELEMETRY_DISABLED=1 pnpm build && cp -r public/_redirects out/"
  publish = "apps/website/out"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--version"
  NETLIFY_USE_PNPM = "true"
  PNPM_FLAGS = "--no-frozen-lockfile"
  NEXT_BUNDLE_EXTERNALS = "false"
  NODE_OPTIONS = "--max-old-space-size=4096"

# Disabilitiamo il plugin Next.js per evitare conflitti con l'output statico
# [[plugins]]
#  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[functions]
  external_node_modules = ["gamba-core-v2"]
