[build]
  base = "."
  command = "pnpm install --no-frozen-lockfile && NEXT_TELEMETRY_DISABLED=1 pnpm turbo run build --filter=website^..."
  publish = "apps/website/.next"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--version"
  NETLIFY_USE_PNPM = "true"
  PNPM_FLAGS = "--no-frozen-lockfile"
  NEXT_BUNDLE_EXTERNALS = "false"
  NODE_OPTIONS = "--max-old-space-size=4096"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  external_node_modules = ["gamba-core-v2"]
