[build]
  base = "."
  command = "echo 'Bypassing build step'"
  publish = "New1-master/apps/website/public"

[build.environment]
  NODE_VERSION = "18"

# Redirezione fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
